import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import React from 'react';

import Header from '../components/Header';
import NavBar from '../components/NavBar';
import Results from '../components/Results';
import { Result } from '../interfaces';
import { MovieListKeys } from '../types';
import { movieList } from '../utils/requests';

interface Props {
  results: Result[];
}

const Home: NextPage<Props> = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NavBar />
      <Results results={results} />
    </div>
  );
};

export const getServerSideProps = async (context: NextPageContext) => {
  const genre = context.query.genre as MovieListKeys;

  const request = await fetch(
    `https://api.themoviedb.org/3${movieList[genre]?.url}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
};

export default Home;
